# Configuración para GitHub Codespaces
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - JWT_SECRET=codespaces_jwt_secret_2024
      - PORT=3001
    command: ["dockerize", "-wait", "file:///app/data", "-timeout", "30s", "npm", "start"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - /workspace:/workspace
