name: Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Allow only one concurrent deployment
concurrency:
  group: "netlify-deploy"
  cancel-in-progress: false

jobs:
  # Build and Deploy job
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.netlify-deploy.outputs.deploy-url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          # Add environment variables needed for build
          REACT_APP_GOOGLE_SCRIPT_URL: ${{ secrets.REACT_APP_GOOGLE_SCRIPT_URL || '' }}
          
      - name: Deploy to Netlify
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
